server:
  port: 8080


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.221:3306/dby?characterEncoding=UTF-8
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    poolPreparedStatements: true
    maxOpenPreparedStatements: 2
    validationQuery: SELECT 1 FROM DUAL
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    filters: stat,wall,log4j
    allow: 192.168.3.2,127.0.0.1
    deny: 192.168.3.2
    loginUsername: jackson
    loginPassword: 123!@#
    resetEnable: false
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${system.upload}

system:
  login:
    limit: true # 是否开启登陆失败次数限制
    captchaEnable: true # 是否开启验证码
    retryCount: 5 #登录失败最大次数
  upload: /Users/mitnick/company/upload/

  security:
     spring-session-open: false # 是否开启spring session 如果是多机环境需要开启 true ／false
     session-invalidate-time: 1800000  #session 失效时间，只在单机环境下生效，多机环境在springSessionConfig类中配置
     session-validation-interval: 900000 #多久检测一次失效的session
     cookie-remember-me: 432000
  maxSession: 1