package com.dingxuan.atrm.core.dao.assets;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IsysConfigSDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Fri Apr 13 11:06:17 CST 2018
     */
    long countByExample(sysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Fri Apr 13 11:06:17 CST 2018
     */
    int deleteByExample(sysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Fri Apr 13 11:06:17 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Fri Apr 13 11:06:17 CST 2018
     */
    int insert(sysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Fri Apr 13 11:06:17 CST 2018
     */
    int insertSelective(sysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Fri Apr 13 11:06:17 CST 2018
     */
    List<sysConfig> selectByExample(sysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Fri Apr 13 11:06:17 CST 2018
     */
    sysConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Fri Apr 13 11:06:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") sysConfig record, @Param("example") sysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Fri Apr 13 11:06:17 CST 2018
     */
    int updateByExample(@Param("record") sysConfig record, @Param("example") sysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Fri Apr 13 11:06:17 CST 2018
     */
    int updateByPrimaryKeySelective(sysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Fri Apr 13 11:06:17 CST 2018
     */
    int updateByPrimaryKey(sysConfig record);
}